import React, { useState } from "react";
import styles from "./UploadScan.module.css";
import jsPDF from "jspdf";

function UploadScan({ patient }) {
  const [selectedImage, setSelectedImage] = useState(null);
  const [imageFile, setImageFile] = useState(null);
  const [tumorDetected, setTumorDetected] = useState(null);
  const [predictionLabel, setPredictionLabel] = useState(""); // ✅ backend "prediction"
  const [tumorType, setTumorType] = useState("");
  const [confidence1, setConfidence1] = useState(null);
  const [confidence2, setConfidence2] = useState(null);
  const [scanId, setScanId] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleImageUpload = (e) => {
    if (!patient?.name || !patient?.age) {
      alert("Please enter patient info first!");
      return;
    }
    const file = e.target.files[0];
    if (file) {
      setImageFile(file);
      setSelectedImage(URL.createObjectURL(file));
      setTumorDetected(null);
      setPredictionLabel("");
      setTumorType("");
      setScanId(null);
    }
  };

  const analyzeMRI = async () => {
    if (!imageFile) {
      alert("Please upload an MRI image first");
      return;
    }
    const formData = new FormData();
    formData.append("file", imageFile);
    formData.append("patient_name", patient.name);
    formData.append("patient_age", patient.age);
    formData.append("patient_gender", patient.gender || "");

    try {
      setLoading(true);
      const response = await fetch("http://localhost:8000/predict", {
        method: "POST",
        body: formData,
      });
      const data = await response.json();
      console.log("Predict response:", data);

      setTumorDetected(data.tumor);          // "Yes" / "No"
      setPredictionLabel(data.prediction);  // ✅ show predicted label
      setConfidence1(data.confidence1);
      setScanId(data.scan_id);
    } catch (error) {
      console.error("Prediction Error:", error);
    } finally {
      setLoading(false);
    }
  };

  const predictType = async () => {
    if (!scanId) {
      alert("No scan ID found. Run detection first.");
      return;
    }
    const formData = new FormData();
    formData.append("file", imageFile);
    formData.append("scan_id", scanId);

    try {
      setLoading(true);
      const response = await fetch("http://localhost:8000/classify", {
        method: "POST",
        body: formData,
      });
      const data = await response.json();
      console.log("Classify response:", data);

      setTumorType(data.tumor_type);
      setConfidence2(data.confidence2);
    } catch (error) {
      console.error("Classification Error:", error);
    } finally {
      setLoading(false);
    }
  };

  const downloadReport = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text("Brain Tumor Detection Report", 20, 20);

    doc.setFontSize(12);
    doc.text(`Patient Name: ${patient?.name}`, 20, 40);
    doc.text(`Age: ${patient?.age}`, 20, 50);
    doc.text(`Gender: ${patient?.gender}`, 20, 60);
    doc.text(`Scan Date: ${new Date().toLocaleString()}`, 20, 70);

    doc.text(`Tumor Detected: ${tumorDetected}`, 20, 90);
    if (confidence1 !== null) {
      doc.text(`Detection Confidence: ${(confidence1 * 100).toFixed(2)}%`, 20, 100);
    }
    doc.text(`Prediction Label: ${predictionLabel || "-"}`, 20, 110);
    doc.text(`Tumor Type: ${tumorType || "-"}`, 20, 120);
    if (confidence2 !== null) {
      doc.text(`Classification Confidence: ${(confidence2 * 100).toFixed(2)}%`, 20, 130);
    }

    doc.setFontSize(10);
    doc.text(
      "Disclaimer: This report is generated by an AI system. It is not a medical diagnosis. Please consult a qualified doctor.",
      20,
      160,
      { maxWidth: 170 }
    );

    doc.save("Patient_Report.pdf");
  };

  return (
    <div className={styles.card}>
      <h3>Upload MRI Scan</h3>
      <input type="file" accept="image/*" onChange={handleImageUpload} />
      {selectedImage && <img src={selectedImage} alt="MRI Preview" className={styles.preview} />}

      <button onClick={analyzeMRI} disabled={!patient?.name || !patient?.age}>
        {loading ? "Analyzing..." : "Analyze MRI"}
      </button>

      {tumorDetected !== null && (
        <div className={styles.resultCard}>
          <p>Tumor Detected: <strong>{tumorDetected}</strong></p>
          {confidence1 && <p>Confidence: {(confidence1 * 100).toFixed(2)}%</p>}
          <p>Prediction Label: {predictionLabel || "-"}</p>
          {tumorDetected === "Yes" && (
            <button onClick={predictType}>Predict Tumor Type</button>
          )}
        </div>
      )}

      {tumorType && (
        <div className={styles.resultCard}>
          <p>Tumor Type: <strong>{tumorType}</strong></p>
          {confidence2 && <p>Confidence: {(confidence2 * 100).toFixed(2)}%</p>}
        </div>
      )}

      {tumorDetected !== null && (
        <div className={styles.reportCard}>
          <h3>Generate Report</h3>
          <button onClick={downloadReport}>Download PDF Report</button>
        </div>
      )}
    </div>
  );
}

export default UploadScan;
