import React from "react";
import DashboardLayout from "../components/layout/DashboardLayout";
import styles from "./Disclaimer.module.css";

const Disclaimer = () => {
  return (
    <DashboardLayout>
      <div className={styles.container}>
        <div className={styles.alertBox}>
          <h2 style={{color: "#b91c1c"}}>Medical Disclaimer</h2>

          <p>
            This system is an AI-based medical image prediction tool developed 
            for educational and research purposes only.
          </p>

          <p>
            The predictions generated by this system are based on a trained 
            machine learning model and may contain inaccuracies or errors.
          </p>

          <p>
            This application is not intended to replace professional medical 
            diagnosis, clinical judgment, or treatment decisions.
          </p>

          <p>
            Users are strongly advised to consult a certified radiologist or 
            qualified medical professional for accurate diagnosis and medical advice.
          </p>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default Disclaimer;