import React from "react";
import DashboardLayout from "../components/layout/DashboardLayout";
import styles from "./Disclaimer.module.css";
import { FaExclamationTriangle, FaUserMd, FaRobot, FaShieldAlt, FaGavel } from "react-icons/fa";

const points = [
  {
    icon: <FaRobot />,
    title: "AI-Based Tool",
    text: "This system is an AI-based medical image analysis tool developed strictly for educational and research purposes. It is not a certified medical device.",
  },
  {
    icon: <FaExclamationTriangle />,
    title: "Prediction Accuracy",
    text: "Predictions generated by this system are based on a trained machine learning model and may contain inaccuracies or errors. Results should not be considered definitive.",
  },
  {
    icon: <FaUserMd />,
    title: "Professional Consultation Required",
    text: "This application does not replace professional medical diagnosis, clinical judgment, or treatment decisions. Always consult a certified radiologist or qualified physician.",
  },
  {
    icon: <FaShieldAlt />,
    title: "User Responsibility",
    text: "Users are responsible for how they use the outputs of this system. The developers assume no liability for any medical decisions made based on system predictions.",
  },
  {
    icon: <FaGavel />,
    title: "Legal Notice",
    text: "Use of this system implies acceptance of these terms. The system is provided as-is for academic demonstration and does not constitute medical advice of any kind.",
  },
];

const Disclaimer = () => {
  return (
    <DashboardLayout>
      <div className={styles.page}>

        {/* Alert Banner */}
        <div className={styles.alertBanner}>
          <FaExclamationTriangle className={styles.alertIcon} />
          <div>
            <h2 className={styles.alertTitle}>Medical Disclaimer</h2>
            <p className={styles.alertSubtitle}>
              Please read the following carefully before using this system.
            </p>
          </div>
        </div>

        {/* Points */}
        <div className={styles.grid}>
          {points.map((point, idx) => (
            <div
              key={idx}
              className={styles.card}
              style={{ animationDelay: `${idx * 0.07}s` }}
            >
              <div className={styles.cardIcon}>{point.icon}</div>
              <div>
                <h3 className={styles.cardTitle}>{point.title}</h3>
                <p className={styles.cardText}>{point.text}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Footer Note */}
        <div className={styles.footerNote}>
          This system is developed as a Final Year Project for academic purposes only.
          It is not approved for clinical use.
        </div>

      </div>
    </DashboardLayout>
  );
};

export default Disclaimer;