import { FaExclamationTriangle } from "react-icons/fa";
import { useNavigate } from "react-router-dom";

function Disclaimer({ isGate = false }) {
  const navigate = useNavigate();

  const handleContinue = () => {
    // isGate true itts mean lgin page ke abad wala disclaimer agr false to simple dashboard wala disclaimer
    if (isGate) {
      sessionStorage.setItem("disclaimer_accepted", "true");
      navigate("/dashboard");
    } else {
      navigate("/dashboard");
    }
  };

  return (
    <div className="w-full min-h-screen bg-gray-200 flex justify-center items-start p-4 pt-10 md:pt-16">
      <div className="w-full max-w-3xl bg-white shadow-xl rounded-xl p-6 md:p-10 text-center border-b-8 border-r-8 border-red-700">

        <h2 className="text-3xl md:text-5xl font-semibold text-blue-950 flex items-center justify-center gap-3 flex-wrap">
          <FaExclamationTriangle className="text-red-700" />
          Disclaimer
        </h2>

        <p className="pt-4 text-justify text-gray-600 text-sm md:text-lg leading-relaxed">
          This application utilizes an Artificial Intelligence (AI) model to assist in the
          detection and classification of brain tumors from MRI images. The system analyzes
          uploaded images and provides predictions based on patterns learned during the model's
          training process. However, the results generated by this application are intended
          solely for research, educational, and demonstration purposes. Although efforts have
          been made to develop and evaluate the model carefully, the predictions may not always
          be accurate and may occasionally produce incorrect results such as false positives or
          false negatives. Therefore, this system should not be considered a substitute for
          professional medical advice, diagnosis, or treatment. Users are strongly encouraged
          to consult a qualified healthcare professional or medical specialist for accurate
          diagnosis and appropriate medical decisions. The developers of this application are
          not responsible for any medical or clinical decisions made based on the predictions
          provided by this system.
        </p>

        <div className="mt-6">
          <button
            className="bg-blue-950 text-white px-6 py-2 rounded-lg  active:scale-95 text-sm md:text-base transition duration-300 hover:bg-blue-900 shadow-blue-900 hover:shadow-xl hover:-translate-y-0.5 hover:shadow-blue-500/40"
          
            onClick={handleContinue}
          >
            {isGate ? "I Understand & Continue" : "I Understand & Continue"}
          </button>
        </div>

        <p className="text-xs md:text-sm text-gray-600 mt-5 leading-relaxed">
          This project is developed as part of a Final Year Project for educational purposes.
        </p>

      </div>
    </div>
  );
}

export default Disclaimer;